[project]
name = "openv"
version = "0.1.0"
description = "Bootstrap your UNIX environment from a dotfiles repository"
readme = "README.md"
authors = [
    { name = "Oleg Stepanov", email = "oleg.stepanov@gmail.com" }
]
requires-python = "==3.11.*"
license = { text = "MIT" }
dependencies = [
    "questionary>=2.0",
    "rich>=13.0",
]

[project.scripts]
openv = "openv.cli:main"

[build-system]
requires = ["uv_build>=0.8.14,<0.9.0"]
build-backend = "uv_build"
